export const cards = [
   {
      id: 'e1',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e2',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },

   {
      id: 'e3',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e4',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e5',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e6',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e7',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e8',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
];
