export const cards = [
   {
      id: 'e1',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      favoriteStatus: true,
      messageStatus: true,
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e2',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира ',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e3',
      img: 'https://dyatkovo.ru/upload/iblock/c7e/oiboz97b4bhapc3e2xwf4qlhbc3h299h.jpg',
      price: '50000',
      favoriteStatus: true,
      messageStatus: true,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e4',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e5',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: true,
      messageStatus: true,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e6',
      img: 'https://evmaster.net/wp-content/uploads/2021/05/13.jpeg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e7',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e8',
      img: 'https://images.cdn-cian.ru/images/kvartira-moskva-prospekt-vernadskogo-2187471962-1.jpg',
      price: '50000',
      favoriteStatus: true,
      messageStatus: true,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e9',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: true,
      messageStatus: true,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e10',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e11',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e12',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e13',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e14',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e15',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: true,
      messageStatus: true,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
   {
      id: 'e16',
      img: 'https://dyatkovo.ru/upload/iblock/50e/mo21t3sui5kmt4me0lqi9vmsr15w5b6g.jpg',
      price: '50000',
      favoriteStatus: false,
      messageStatus: false,
      title: '2х комнатная квартира',
      address: 'Москва, р-н Центральный',
      description: '2-комн. кв. 59 м² 3/8 этаж',
   },
];
