export const PATHS = {
   HOME: '/',
   USER: {
      ROOT: '/user',
      CREATE_AD: '/user/create-ad',
      PROFILE: '/user/my-page/profile',
      DETAIL_INFO: '/user/detail-info',
      CATEGORY: '/user/category/:subCategory',
      DETAILS: '/user/details/:id',
      MY_PAGE: '/user/my-page',
      MY_ADS: '/user/my-page/my-listings',
      RECOMMENDATIONS: '/user/recommendations',
      MAIN_PHP: '/user/main.php',
   },
   ADMIN: {
      ROOT: '/admin',
      DASHBOARD: '/admin/dashboard',
      USERS: '/admin/users',
      ADS: '/admin/ads',
      CATEGORIES: '/admin/categories',
      MODERATION: '/admin/moderation',
      COMPLAINTS: '/admin/moderation/complaints',
      COMMENTS: '/admin/moderation/comments',
      MAILING: '/admin/mailing',
      ADD_MAILING: '/admin/users/add-mailing',
      ADD_ADMIN: '/admin/add-administrator',
      ADVERTISING: '/admin/advertising',
   },
   FALLBACK: '*',
}
